name: 部署 GitHub Pages

on:
  # 在推送到 main 分支時執行
  push:
    branches: ["main"]
  # 允許手動從 Actions 標籤頁執行
  workflow_dispatch:

# 設定 GITHUB_TOKEN 權限
permissions:
  contents: read
  pages: write
  id-token: write

# 允許一個並發部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 單一工作部署
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: 列出檔案內容
        run: |
          echo "目前目錄內容:"
          ls -la
      
      - name: 上傳成品
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
