name: 自動更新工具目錄
on:
  push:
    branches:
      - main
    paths:
      - '**.html'      # 符合任何目錄下的 HTML 檔案
      - '!index.html'  # 排除 index.html
  workflow_dispatch:   # 允許手動觸發

jobs:
  update-toc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 簽出程式碼
        uses: actions/checkout@v3
      
      - name: 設定 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: 執行目錄更新腳本
        run: python .github/scripts/update_toc.py
      
      - name: 檢查是否有更改
        id: check_changes
        run: |
          git diff --quiet index.html || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: 提交並推送更新
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add index.html
          git commit -m "更新: 自動更新工具目錄"
          git push
